mapbox/ecs-conex

Dockerfile
Corresponds to an update of the ECS-optimized AMIs https://aws.amazon.com/about-aws/whats-new/2016/05/amazon-ec2-container-service-supports-docker-1-11/
=> docker@1.11.1

test/manual.ecs-conex.sh
Adds a script to manually run the ecs-conex docker image. This is just there to help provide the image with the proper environment, but may be a useful way to start thinking about testing.
cc @karenzshea
=> run ecs-conex manually

cloudformation/ecs-conex.template.json, ecs-conex.sh
Fixes #11 which was misdiagnosed -- the failure message arrived when an just-merged branch is deleted.
=> Use deleted flag on push event to ignore branch deletes

ecs-conex.sh
In situations where a `docker build` needs to fetch private resources (say, from S3), the build command needs to be supplied with `--build-arg`s defining credentials to access those resources.
This PR allows you to write a Dockerfile that relies on [ARG instructions](https://docs.docker.com/engine/reference/builder/#arg) for `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN`.
ecs-conex will be running on an EC2. At build-time, it will 
- check the EC2 metadata service and acquire credentials for any available IAM role
- check the Dockerfile for ARG instructions
- if there are credentials to provide, and ARG instructions to use the credentials, then ecs-conex will provide those credentials as `--build-arg`s to `docker build`
cc @jacquestardie
=> Provide aws credentials as build-args

scripts/watch.sh
Hit this little bump when attempting to watch a repo with a remote that included `.git`
=> Strip .git suffix from origin

cloudformation/ecs-conex.template.json, readme.md
**TL;DR** leaving out the explicit connection options for the `syslog` driver works on ECS. Hunches on why this wasn't working below...
------
@rclark I wasn't able to see any of the logging output of `ecs-conex` in the syslog of the container instance and had a hunch that `localhost` in the context of the container might be a bit suspect. I don't know for sure but these two clues made me think that connecting to the host instance this way wasn't going to fly.
- Docker docs on how the syslog driver behaves without options. The note about using a socket by default ... :thought_balloon: 
> syslog-address specifies the remote syslog server address where the driver connects to. If not specified it defaults to the local unix socket of the running system.
- Various literature making it sound …
=> Use default Docker syslog driver settings

cloudformation/ecs-conex.template.json, ecs-conex.sh, test/manual.ecs-conex.sh, test/utils.test.sh, utils.sh
This PR adds an `NPMToken` stack parameter, creates an npmrc file before building, and deletes the npmrc file after the image has successfully finished. The npmrc file is a prerequisite to install private npm modules in the pushing repository.
@rclark, I think this should work if it's run before the [`docker build` step](https://github.com/mapbox/ecs-conex/blob/8b96a95aa2e27f7b92fa6ff5edd4cfd827ddfd56/ecs-conex.sh#L138-L139). Would love your thoughts on this.
cc @willwhite @emilymcafee @yhahn
=> Adds NPMToken stack param

cloudformation/ecs-conex.template.json
Adds appropriate prefixes to worker logs as well as watcher logs.
=> log prefixing for worker task

test/utils.test.sh, utils.sh
@rclark, this PR addresses [the test case issue you brought up](https://github.com/mapbox/ecs-conex/commit/ba633461897e03d7b9c2054ddd2d55863d3c3b54#commitcomment-18385297). I think it may have been a vestige, since it didn't seem necessary for tests to pass.
=> Removes test case from credentials fxn

cloudformation/ecs-conex.template.json
Refs [PR #26 ](https://github.com/mapbox/ecs-conex/pull/26#issuecomment-235013891)
@rclark, is this all that needs to be done to make this parameter optional? Setting the default to an empty string should cause this to evaluate false and not append the `NPMAccessToken` build argument.
=> Makes NPMAccessToken optional

package.json
Allows `npm link` to put `watch.sh` on your $PATH.
=> Use npm link for watch script

scripts/watch.sh
Got this error while trying to run `ecs-conex-watch` on my stack:
```
console.log(The name of the CloudWatch LogGroup where ecs-conex logs are sent      LogGroup           ecs-conex-production-WatchbotLogGroup-1UK1S8HSB9JV8
^^^
SyntaxError: missing ) after argument list
at Object.exports.runInThisContext (vm.js:53:16)
at Object.<anonymous> ([eval]-wrapper:6:22)
at Module._compile (module.js:434:26)
at node.js:567:27
at doNTCallback0 (node.js:408:9)
at process._tickCallback (node.js:337:13)
```
I hadn't configured `aws-cli` to always output JSON by default, so the output of the [`--describe-stacks`](https://github.com/mapbox/ecs-conex/blob/master/scripts/watch.sh#L11) stumped the watch script. 😅  Initially I thought it was because I had an older version of `aws-cli`, but the problem …
=> small change to explicitly output json in `aws describe-stacks ...` cmd

ecs-conex.sh
This PR hides`git clone` output.
Currently, repositories that take a while to clone have somewhat spammy logs.
```bash
started task for webhook: {"ref":"refs/heads/master","after":"81f728b7d8ef5c73b85ebef0b077ded481d2c80c","before":"e784e3617a6f48b8d3003d7313a32e79f732d21a","deleted":false,"repository":{"name":"pxm","owner":{"name":"mapbox"}},"pusher":{"name":"jacquestardie"}}
Checking out files:  50% (303/600)
Checking out files:  51% (306/600)
Checking out files:  52% (312/600)
...
Checking out files:  99% (342/600)
...
```
cc @rclark
=> Silence git clone

cloudformation/ecs-conex.template.js, package.json, test/template.test.js
- Uses watchbot@2.2.4, but opts into `alarmOnEachFailure` to preserve existing alarm behavior
- Uses `@mapbox` namespaced modules
- Removes logAggregationFunction
todo
cc @rclark
=> watchbot > 2.0

package.json
Adds the `PendingTime` metric to ecs-conex. Before merging, we should add an alarm for long times spent in PENDING.
cc/ @emilymcafee @l-r @yhahn @rclark
=> Bump ecs-watchbot to 2.3.0

package.json
In order to upgrade webhook function runtime to nodejs4.3 (ref https://github.com/mapbox/ecs-watchbot/pull/147)
cc @rclark
=> upgrade watchbot to 2.4.0

Dockerfile, package.json, scripts/bootstrap.sh, utils.sh
An alternative to #102, this approach would include tarballs for multiple docker versions in conex's docker image, select and extract the correct one at runtime.
cc @vsmart @yhahn 
refs #90
=> Include multiple versions of docker, extract at runtime

cloudformation/ecs-conex.template.js, docs/alarms.md
Adds an alarm on the pending time for ecs-conex. I chose 2 minutes since there's only one point over the last 24 hours of the metric that goes above it - but I'm willing to raise it.
cc/ @rclark @emilymcafee @xrwang
=> Add pending metric alarm for conex

readme.md
Hi, While working on this https://github.com/mapbox/ecs-or-bust/issues/3, I faced an issue where ecs-conex wasn't able to build my commit as I added private npm modules. But that didn't come as an insight to me , because in that commit I didn't change any thing in dockerfile but in package.json and couldn't figure out the reason of failing build. But from ecs-conex logs looked like some authentication issue and  realized the problem. Therefore this might be helpful for anyone else referring to readme file. 
cc @emilymdubois
=> easy access to private npm module doc

Dockerfile
This supports the newest ecs-optimized AMI.
cc @jakepruitt
=> Include docker 17.06.2-ce

Dockerfile
Adds docker-17.09.1-ce.tgz to list of supported docker versions.
Sorry everyone.
cc/ @allierowan @rclark
=> Add docker-17.09.1-ce.tgz

cloudformation/ecs-conex.template.js, ecs-conex.sh, test/utils.test.sh, utils.sh
Adds two parameters. If I specify them as follows:
- ImageBucketPrefix: my-bucket
- ImageBucketRegions: us-east-1 ap-southeast-1
... then on commit, image tarballs will be written to 
```
s3://my-bucket-us-east-1/images/my-service/gitsha.tar.gz
s3://my-bucket-ap-southeast-1/images/my-service/gitsha.tar.gz
```
I'd like to get away from this naming convention but I can't come up with a reasonable way to do it given CloudFormation's limitations on CommaDelimitedList parameters. Even with this solution I'm pretty unhappy giving `PutObject` permission to 
```
cf.sub('arn:aws:s3:::${ImageBucketPrefix}-*/images/*')
```
fixes #88 
cc @jakepruitt @zmully
=> Make image tarballs

scripts/bootstrap.sh
On linux git requires `HEAD` to be fully uppercased.
Error:
```
++ git rev-parse head
fatal: ambiguous argument 'head': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
=> Bootstrap should parse git HEAD

.circleci/config.yml, cloudformation/ecs-conex.template.js, package-lock.json, package.json, test/cleanup.test.js
closes #133 
>  UPDATE_FAILED ConexWebhookFunction: ZipFile can only be used when Runtime is set to either of nodejs, nodejs4.3, nodejs6.10, python2.7,
So going with Node6 for the lambda runtime now instead of Node8. 
The test file changes were needed for the `sinon` dependency upgrade.
=> update runtime to 6; refresh dependencies
