cloudformation/ecs-conex.template.json
=> HMAC signature for webhook request validation

cloudformation/ecs-conex.template.json
Hard-wires a number of Watchbot parameters.
=> Simplify cloudformation parameters

Dockerfile, cloudformation/ecs-conex.template.json
This reconfigures so that logs are sent from containers to syslog instead of written to a log file on the host EC2.
=> Logs to syslog

ecs-conex.sh
=> Github status api

circle.yml
See https://github.com/mapbox/ecs-conex/issues/1#issuecomment-223722679.
=> Add minimal circle.yml config

ecs-conex.sh, test/utils.test.sh, utils.sh
=> Exit 3 if a job has been tried 3 times. Refs #17

cloudformation/ecs-conex.template.json
=> Tag logs with stack info

cloudformation/ecs-conex.template.json, test/manual.ecs-conex.sh, test/utils.test.sh, utils.sh
Swapping out the nomenclature here
cc @rclark @yhahn
=> NPMToken -> NPMAccessToken

docs/npm.md
=> Adds npm private module doc

cloudformation/ecs-conex.template.json, readme.md, scripts/send-job.sh
See https://github.com/mapbox/ecs-watchbot/blob/master/changelog.md#005
Todo:
- add documentation about the format of these messages and how to start debugging from them
=> Better failure notifications

ecs-conex.sh, test/utils.test.sh, utils.sh
Refs https://github.com/mapbox/ecs-conex/issues/40.
cc @rclark @emilymcafee
=> Two lies makes a trap

cloudformation/ecs-conex.template.json, ecs-conex.sh, test/utils.test.sh, utils.sh
- Implements @rclark's master plan from https://github.com/mapbox/ecs-conex/issues/30.
- Includes https://github.com/mapbox/ecs-conex/pull/47.
Will stage and confirm all the things work.
cc @rclark
=> Cleanup time

Dockerfile, cloudformation/ecs-conex.template.json, ecs-conex.sh
Write logs to CloudWatch logs instead of syslog --> /var/log/messages
refs https://github.com/mapbox/ecs-watchbot/issues/30 & https://github.com/mapbox/ecs-watchbot/issues/31
=> Switch to cloudwatch logs

test/utils.test.sh, utils.sh
I think this fixes https://github.com/mapbox/ecs-conex/issues/51.
=> Remove images by image id

ecs-conex.sh, test/utils.test.sh, utils.sh
=> Login before building the image

cloudformation/ecs-conex.template.js
=> Calculate signature against bytes, not str

cloudformation/ecs-conex.template.js, package.json
Yay for well-named log streams.
=> watchbot@0.0.13

cloudformation/ecs-conex.template.js
Fallout of :hocho: ClusterRole
=> Add permission to ecr:BatchCheckLayerAvailability

cloudformation/ecs-conex.template.js
=> Add more perms

docs/npm.md
about using NPMAccessToken on local Docker builds.
=> small npm amendment

cloudformation/ecs-conex.template.js
Adds a stack parameter that allows you to set a desired worker concurrency.
=> Configurable concurrency

changelog.md, test/utils.test.sh, utils.sh
Resolves #60 
@rclark this is still WIP but can you take a look and see if this is on the right track?
=> push tags before sha, only if tag doesn't exist

changelog.md, ecs-conex.sh, test/utils.test.sh, utils.sh
- Adds ability to pass in `GithubAccessToken` as a build-arg to a docker file per #76 
cc @jacquestardie @rclark
=> adding ability to pass in github token to dockerfile

changelog.md, package.json
=> Upstream condition for log forwarding

docs/debugging-failures.md, docs/getting-started.md, docs/logging.md, docs/npm.md, docs/removing-images.md, readme.md
This PR pulls documentation usage details out of the main `readme.md` and into specific files in the `docs/` directory.
cc @rclark @emilymcafee
=> Documentation refresh

scripts/cleanup.js, test/cleanup.test.js
Finally hit the 1000 image ECR limit in one of our repos ^_^
cc @emilymdubois @mapbox/platform
=> Y1K bug redux

changelog.md, package.json, scripts/watch.sh, test/watch.test.sh
Fixes https://github.com/mapbox/platform/issues/633
=> Fail helpfully when GithubAccesToken does not have adequate permissions

Dockerfile
=> Updated image for docker 17.03.2

Dockerfile
=> New docker static binary urls

ecs-conex.sh
=> Loud build logs

Dockerfile
=> Add hard timeout to workers

Dockerfile, package-lock.json, package.json, scripts/cleanup.js, test/cleanup.test.js, test/utils.test.sh, utils.sh
@arunasank I made a lot of changes to the existing code from #97. Wanted to open it up as a PR to provide some insight into why I made this set of changes. See below.
=> ECR cleanup code review & overhaul

docs/removing-images.md
cc @emilymdubois @jacquestardie
=> Document the cleanup --region option

docs/getting-started.md
After getting help from @jakepruitt setting up ecs-conex on api-accounts, @dputtick and I think that this language is clearer. If anything is misleading, we'd welcome feedback to clarify our own understanding of the ecs-conex workflow.
/cc @rclark
=> Clarify getting started language

Dockerfile
=> New version of docker on ecs hosts

test/utils.test.sh
These tests were accidentally commented out in #89. 
cc @taraadiseshan
=> Uncomment tests.

utils.sh
cc/ @mapbox/platform-engine-room
=> Fix link to alarm docs

Dockerfile, circle.yml, cloudformation/ecs-conex.template.js, ecs-conex.sh, package-lock.json, package.json
Uses watchbot version 4, taking in a few things with it:
1. an upgrade to node 8
2. move from the watchbot webhooks to using https://github.com/mapbox/hookshot
Going to need to fix up some of the tests by the looks of it, as well as test this out across all of our different stacks.
cc/ @mapbox/platform-engine-room
=> With watchbot 4

scripts/watch.sh
Closes #139.
cc/ @ingalls @rclark
=> Use the new Outputs for the watch.sh script

.circleci/config.yml, circle.yml, test/utils.test.sh
Closes #136 
cc @mapbox/assembly-line
=> Migrate to Circle 2.0

Dockerfile
=> Use binary watchbot

changelog.md
ref #143 
Will publish 0.5.0 once this is merged.
=> changelog@v0.5.0

Dockerfile, package-lock.json, package.json
Running on the latest watchbot will give us WorkerDuration metrics re-introduced in https://github.com/mapbox/ecs-watchbot/pull/284. 
cc @mapbox/assembly-line
=> Watchbot@4.11.1 for JobDuration metrics
